### ISSUE TITLE
Can we be helpful on breaking arcdps updates?

### ISSUE THREAD

**Issue by grekker** [typedeck0/Know-thy-enemy#25]
Hello! I have come to find this addon indispensable, and I say "oh no" when I see an arcdps update because KTE often breaks and stops rendering the window with new arc updates (like yesterday's, and KTE is not initing again).

You're quite good about getting updates out to fix this within a few days.

I've checked the commits and I don't see file commits on these fixes, I'm guessing it's something you're doing in the more secret part of the project to address whatever arc is doing that breaks KTE.

Is there something we (your appreciative users) can do to help break this cycle? I hesitate to not update arcdps, since that comes with its own headaches and possible game crashes. Can we help make KTE more resilient in some way? Or submit some kind of pull request that would be useful when there is an arcdps update?

Thanks!

**Comment by typedeck0** [comment]
Ive found it best to update once arcdps is breaking (content mismatch). Ive disabled auto-updates on arcdps and im still using quite an old arcdps and have not had any problems. I have to manually update KTE with some hardcoded addresses inside of arcdps itself, which change almost every update. 

One thing ive been meaning to do is pattern match some arcdps signatures to find these hardcoded addresses dynamically, but updating has become quite easy ever since the arcdev has stopped trying to manipulate his code to circumvent KTE.

**Comment by grekker** [comment]
Thanks for replying! Glad you aren't being actively stymied anymore.
